### ISSUE TITLE
Hashids compatibility between C version and Swift version

### ISSUE THREAD

**Issue by prudent-penguin** [tzvetkoff/hashids.c#24]
Hello,

I am asking this here because no one seems to be facing this issue.
I am using Hashids swift version to encode an array and I am using C version to decode it with same SALT. The decoding is successful only one time after device reset, and after that every time decoding fails. The C version is 1.1.5 and Swift version is 1.1.0. Though I am not facing this issue if encoding is done using the Java version of Hashids on Android. Java version is 1.0.1.

The C code is:

```
size_t decode_hashids(const char *salt, char *hash, unsigned long long num_array[])
{
  hashids_t *hashids;
  hashids = hashids_init3(salt, MIN_HASH_STRLEN,HASHIDS_DEFAULT_ALPHABET);
 /*MIN_HASH_STRLEN is 6*/
  size_t bytes_decoded = hashids_decode(hashids, hash, num_array);   
  hashids_free(hashids);
  return bytes_decoded;
}
```
The Swift Code is:

```
let hashIds = Hashids(salt: salt , minHashLength: 6)
let id = hashIds.encode(number, number)
```

The call to hashids_init3 or any other function does not modify its value. In fact salt is a string in both languages. So in C its const char[] type and in Swift its String type. The value of salt is kept as a hardcoded value in both languages which does not change for the device (i.e. an arm based processor) where C code is running.

**Comment by tzvetkoff** [comment]
The Swift version and the C version

From your description it seems to me that you're not passing the same hash to the decoding function (or salt.)
Try debugging what you get in your C code, something like:
``` c
printf(">> salt: (%d)[%s], hash: (%d)[%s]\n", strlen(salt), salt, strlen(hash), hash);
```

**Comment by prudent-penguin** [comment]
Thanks for the hint! But the issue here was different. iOS does not send null terminated strings to me, I had to terminate it separately. Solved it both for salt and the hash. Don't mind my noob question. Thanks!
