### ISSUE TITLE
Statement may fall through - warning in GCC7 and upper

### ISSUE THREAD

**Issue by JakubRakus** [tzvetkoff/hashids.c#29]
Compiling under GCC version 7 or greater gives warning `this statement may fall through` for the last line of macro `hashids_shuffle_step(iter)`. Macro is inserted in every case of switch-case in function `void hashids_shuffle(char *str, size_t str_length, char *salt, size_t salt_length)`, and compiler warns because there are no `break`s in cases.

But there is simple solution: just add `__attribute__ ((fallthrough));` at the end of `hashids_shuffle_step(iter)` macro. More here: https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/

**Comment by tzvetkoff** [comment]
The problem with `__attribute__` is that it's not portable, and I want to avoid more feature testing macros.

According to some [research](https://stackoverflow.com/a/45137452) it's enough to add a comment like `/* fall through */` to silence the warning.
Can you confirm it gets the job done on GCC 7 - https://github.com/tzvetkoff/hashids.c/tree/fallthrough (I have GCC 9.1.0 on my Arch and a CLang-something on FreeBSD)

**Comment by JakubRakus** [comment]
Ok, looks like it works. Comment is enough to suppress warnings.

**Comment by tzvetkoff** [comment]
Closing as I made some changes in `master` and along with them I merged the fallthrough warning fix.
